# Generated by Django 4.2.11 on 2024-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_suggestion_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='text',
        ),
        migrations.AddField(
            model_name='complaint',
            name='area',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='coordinates',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(default=2, upload_to='complaints/'),
            preserve_default=False,
        ),
    ]
